apiVersion: apps/v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # This should **not** be in version control - ideally in prod we take from another service like vault
  # base 64 encoded
  password: cGFzc3dvcmQ=
