apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
      # probably dont want to do this in production
  type: NodePort
  selector:
    app: postgres
